config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flats_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flats_params)
    @flat.save
  end

  private

  def flats_params
    params.require(:flat).permit(:name, :address, :host, :description, :picture_url, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <h1 class="text-center">Edit infos about <%=@flat.name%>:</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-6 m-auto">
      <div class="text-center">
        <%=simple_form_for(@flat) do |f|%>
          <%=f.input :name%>
          <%=f.input :address%>
          <%=f.input :host%>
          <%=f.input :description%>
          <%=f.input :picture_url%>
          <%=f.input :number_of_guests%>
          <%=f.input :price_per_night%>
          <%=f.submit%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3 bg-light">
   <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of our <%= Flat.count %> on our website.</p>
      <% else %>
        <p>All <%= Flat.count %> flats.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('<%= flat.picture_url %>') w-100"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <i class="material-icons me-2">people</i><span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex ms-3">
                <i class="material-icons me-2">euro_symbol</i> <%= flat.price_per_night %>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to 'More info', flat_path(flat) %>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'ms-3 text-warning' %>
            <%= link_to "Remove", flat_path(flat),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'ms-3 text-danger'
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4 bg-light">
  <div class="row">
    <div class="col-6 m-auto">
      <h1 class="text-center">Create a new Magic Flat:</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-6 m-auto">
      <div class="text-center">
        <%=simple_form_for(@flat) do |f|%>
          <%=f.input :name%>
          <%=f.input :address%>
          <%=f.input :host%>
          <%=f.input :description%>
          <%=f.input :picture_url%>
          <%=f.input :number_of_guests%>
          <%=f.input :price_per_night%>
          <%=f.submit%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<h1></h1>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=@flat.picture_url%>);">
  <div class="container">
    <h1> <strong><%=@flat.name%></strong></h1>
    <p><%=@flat.address%></p>
  </div>
</div>

<div class="container mt-3 bg-light">
  <p><%=@flat.description%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: url('https://wallpaper.dog/large/762844.jpg')">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Wizarding Air bnb', flats_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="ms-auto flex">
            <form class="flex my-2 my-lg-0">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="">
            </form>
          </div>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary my-2 my-sm-0 ms-2' %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>